# Generated by Django 5.2.3 on 2026-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='subido_alfresco',
            field=models.BooleanField(default=False),
        ),
    ]
