# Generated by Django 5.2.3 on 2026-04-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Países'},
        ),
        migrations.RemoveField(
            model_name='pais',
            name='codigo',
        ),
        migrations.AddField(
            model_name='pais',
            name='codigo_alpha2',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='codigo_alpha3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('documento', 'tipo_documento')},
        ),
    ]
