# Generated by Django 5.2.3 on 2026-04-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoMovimiento',
        ),
    ]
