# Generated by Django 5.2.3 on 2026-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expediente_subido_alfresco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientepersona',
            name='rol',
            field=models.CharField(choices=[('indagado', 'Indagado'), ('victima', 'Víctima'), ('denunciante', 'Denunciante'), ('testigo', 'Testigo')], max_length=20),
        ),
    ]
