# Generated by Django 5.2.3 on 2026-04-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_tipomovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='expedientepersona',
            name='rol',
            field=models.CharField(choices=[('indagado', 'Indagado'), ('victima', 'Víctima'), ('denunciante', 'Denunciante'), ('testigo', 'Testigo'), ('otro', 'Otro')], max_length=20),
        ),
    ]
