# Generated by Django 5.2.3 on 2026-04-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_persona_documento_alter_persona_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='persona',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipo_documento',
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificaciones', to='core.persona')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipodocumento')),
            ],
            options={
                'unique_together': {('tipo_documento', 'numero')},
            },
        ),
    ]
