# Generated by Django 5.2.3 on 2026-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_persona_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='id_origen',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
