# Generated by Django 5.2.3 on 2026-05-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_persona_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
