# Generated by Django 5.2.3 on 2026-06-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmpliacionEstadistica',
            fields=[
                ('nro', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('denuncia_madre', models.BigIntegerField(db_index=True)),
                ('fecha_denuncia', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('dependencia_alias', models.CharField(db_index=True, max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('allanamientos_pos', models.IntegerField(default=0)),
                ('allanamientos_neg', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NovedadEstadistica',
            fields=[
                ('nro', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nunc', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateTimeField(db_index=True)),
                ('dependencia_original', models.CharField(max_length=255)),
                ('dependencia_alias', models.CharField(db_index=True, max_length=50)),
                ('titulo', models.CharField(db_index=True, max_length=255)),
                ('aclarada', models.BooleanField(default=False)),
                ('allanamientos_pos', models.IntegerField(default=0)),
                ('allanamientos_neg', models.IntegerField(default=0)),
            ],
        ),
    ]
