# Generated by Django 5.2.3 on 2026-06-10 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_oficina_activa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoUru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DependenciaPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drbpa.departamentouru')),
            ],
        ),
        migrations.CreateModel(
            name='FichaAusente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(blank=True, max_length=20, null=True)),
                ('nro_caso', models.CharField(max_length=20, unique=True)),
                ('biblio', models.CharField(blank=True, max_length=255, null=True)),
                ('edad_al_momento', models.IntegerField(editable=False, null=True)),
                ('franja_etaria', models.CharField(editable=False, max_length=50, null=True)),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('DIVERSO', 'Diverso')], max_length=20)),
                ('lugar_ausencia', models.CharField(max_length=100)),
                ('nro_sgsp', models.BigIntegerField(db_index=True)),
                ('tipificacion', models.CharField(max_length=100)),
                ('fecha_hecho', models.DateTimeField()),
                ('fecha_ingreso_sgsp', models.DateTimeField()),
                ('divulgacion', models.BooleanField(default=False)),
                ('inau', models.BooleanField(default=False)),
                ('adn', models.BooleanField(default=False)),
                ('bps', models.BooleanField(default=False)),
                ('factores_riesgo', models.TextField(blank=True, null=True)),
                ('fecha_ubicacion', models.DateField(blank=True, null=True)),
                ('estado_persona', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_investigacion', models.CharField(default='ABIERTA', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('departamento_hecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drbpa.departamentouru')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drbpa.dependenciapolicial')),
                ('ingresado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_ausencia', to='core.persona')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='drbpa.fichaausente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
